keithamus/sort-package-json

index.js

see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
/cc @keithamus

Add support for "types" and "typings" from TypeScript

---

index.js
test.js

Move 'private' below 'version'

---

index.js

feat: add support for `xo` key

---

README.md

doc: add supported libraries

---

index.js

Closes #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keithamus/sort-package-json/43)

feat: export sort order

---

README.md

Hi, I have created a VSCode extension using your library.
Adding a link in the README so that people can also use that in VSCode. 🌷

Add VSCode extension mention

---

README.md

Move installation steps to be before usage

---

index.d.ts

index.d.ts typings for TypeScript

---

README.md

Closes https://github.com/keithamus/sort-package-json/issues/63
Sorry for the late reply.

Add link to eslint run with autofix

---

index.js
package-lock.json
package.json

feat: Cross-platform support for glob paths

---

package-lock.json
package.json
test.js

fix: Tests are unreliable in Windows

---

index.js

adds 'type' field to list of properties to sort. references issue #76

adds 'type' field to list of properties to sort

---

index.js

ref: https://www.jsdelivr.com/features#publishing-packages

feat: add `jsdelivr` field

---

README.md
index.js

ref: https://github.com/avajs/ava/blob/master/docs/06-configuration.md

feat: add `ava` field

---

README.md
index.js

ref: https://github.com/istanbuljs/nyc#configuration-files

feat: add `nyc` field

---

test.js

test: remove extra spaces

---

index.js

https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md

feat: add `funding` field

---

README.md
index.js

https://mochajs.org/#configuring-mocha-nodejs

feat: add `mocha` field

---

index.js

https://nodejs.org/api/esm.html#esm_package_exports
fixes: #84

feat: add `exports` field

---

README.md
fixtures/another-not-sorted/package.json
fixtures/not-sorted-1/package.json
fixtures/not-sorted-2/package.json
fixtures/sorted-1/package.json
fixtures/sorted-2/package.json
index.js
test.js

Add a simple implantation of `--check` flag.
Notice: no tests added.
fixes: #67

feat: support `--check` flag

---

.travis.yml
package.json

Setup `sort-package-json --check` on CI

ci: run `sort-package-json` on ci

---

test.js

original test code is not right

test: fix `custom sort order` test

---

test.js

Add `testField` util, and test all fields.

test: add more field test

---

README.md
index.js
package-lock.json
package.json
test.js

1. switch `glob` to `globby`, `globby` is easier to use, and `fast-glob`(globby uses) is faster on large projects.
2. improve `--check` messages, add matched files count
3. add a message when not matching any file

refactor: improve cli

---

index.js
test.js

fix: add `contributors` field back

---

index.js
test.js

`bundledDependencies`/`bundleDependencies` should be an array, not object.
https://docs.npmjs.com/files/package.json#bundleddependencies

fix: sort `bundledDependencies` as array

---

index.js
test.js

`test` property of `directories` field is missing.
https://docs.npmjs.com/files/package.json#directoriestest

fix: add missing `directories.test` property

---

cli.js
index.js
package.json
test.js

Use a separate cli.js, should be easier to maintain.

refactor: separate cli from `index.js`

---

index.js

style: rewrite `sortPrettierConfig`

---

index.js
test.js

with the new `pipe` function, we can easily do this

feat: unique `bundledDependencies-like` fields

---

index.d.ts
package-lock.json
package.json

Setup `lint-staged` to format codes

chore: run format on commit

---

package-lock.json
package.json

chore: update `lint-staged` to v10

---

README.md

It’s **pretty** awesome. :smile:

docs: add related tool prettier-plugin-packagejson

---

index.d.ts

https://github.com/keithamus/sort-package-json/issues/172

fix: try avoid some typescript setting show error

---

package-lock.json

The lock file seems out of sync.

chore: fix lock file

---

cli.js

Fixes the typo introduced in #285

refactor: typo quit -> quiet

---

cli.js
package-lock.json
package.json

https://npmgraph.js.org/?q=globby - 23 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies

chore: switch to tinyglobby

---

.github/workflows/pr.yml
.github/workflows/release.yml

Update actions, add `20` and `22` to matrix, we'll drop others soon.

ci: update workflow files

---

index.js
tests/scripts.js

I'm not sure if the commit message is ok.

feat: revert sort pre/post scripts with colon together (#332)

---

.husky/commit-msg

Fixes the warning message that happens every time you commit to this repository.

fix: husky deprecation
