index.js
test.js

This makes sure that `pretest` always appears before `test` etc.

Group scripts w/ pre/post

---

index.js

Both rollup.js and Webpack 2 now support `module` over `jsnext:main`,
so let's get that added.
See the [Rollup.js docs](https://github.com/rollup/rollup/wiki/pkg.module).

Add `module`, which is the new `jsnext:main`

---

index.js

This commit adds `jest` as a sortable key, right after the linting keys.
[Jest offers tons of configuration](https://facebook.github.io/jest/docs/en/configuration.html) that you might want to stick in your `package.json`. I came across this project because I needed it, and this key was missing based on our own needs. Figuring since Jest is at least one of the most popular testing frameworks out there, this should make the cut.

Add Jest as a sortable key

---

README.md
index.js

This commit adds support for specifying location(s) for the `package.json` file(s) to sort. 
This is particularly useful when you have a monorepo with tons of `package.json` files that need this command.

feat: Add support for specifying location

---

index.js

Since support for `eslintConfig` already exist, I think it would make sense to support the `eslintIgnore` key as well. This key is an alternative to defining ignored paths for eslint in a separate `.eslintignore` file, and consists of an array containing file blobs (should not be sorted).
https://eslint.org/docs/user-guide/configuring#using-eslintignore-in-packagejson

Add support for `eslintIgnore` key

---

index.js

Prettier is a popular code formatter. It has over 21k stars on GitHub and 3M monthly downloads on npm.
It supports configuration via the "prettier" key in `package.json`, so I think it makes sense to add support for it here. https://prettier.io/docs/en/configuration.html

Add support for `prettier` key

---

index.js
package-lock.json
package.json
test.js

This is the same way `npm` does it.
I had to alter a test that was actually testing specifically that the indentation had been formatted, so now it's testing that the indentation hasn't changed.
fixes #33

feat: add support for maintaining `package.json` indentation level when sorting

---

index.js

This adds support for https://github.com/benoror/better-npm-run
I think it makes sense to have it directly below scripts, but I let you be the judge on that.
Note: the build is failing, but I really cannot understand, within the test, why it would. There doesn't seem to be any of your tests that would break from what I added.
Re: oops, wrong branch.

feat: add support for `betterScripts` key, below `scripts`

---

README.md

This pull request adds instructions for how to use a git pre-commit hook to automatically sort the package.json file.

Add automatic instructions

---

index.js
package-lock.json
package.json
test.js

Use [`detect-newline`](https://github.com/sindresorhus/detect-newline) to detect `EOL`
Before, `EOL` is decided by first linebreak, 
After, 
> Detect the dominant newline character of a string
I think it's more reasonable

feat: new eol detection logic

---

index.js
test.js

Make `sortPackageJson` only work on plain objects, prevent something like #64.
Additional a little dry work.

fix: only sort plain objects

---

index.js
test.js

npm offical package [`read-package-json`](https://www.npmjs.com/package/read-package-json) and popular package [`read-pkg`](https://www.npmjs.com/package/read-pkg) and [`read-pkg-up`](https://www.npmjs.com/package/read-pkg-up), add some private keys to json, like `_id`.
This PR make those private keys always at bottom. so we can easy read -> sort -> write, like this
```js
const {path, packageJson} = await readPkg()
const sorted = sortPackageJson(packageJson)
await writePkg(path, sorted)
```

feat: support private keys

---

index.js
package-lock.json
package.json
test.js

Not sure is this #20 requested, we should sort them anyway.

feat: sort husky hooks

---

index.js
test.js

Make custom sortOrder prepend to defaultSortOrder, instead of override it, so user only need send keys that must on top, the rest known fields still sort by defaultOrder.
Should be much easier to use.

feat: prepend custom order to default sort order

---

index.js
test.js

`man` `os` `cpu` are all `array`. 
for `os` and `cpu`, they support negative values.
So, in theory it could be `['darwin', '!darwin']`, order should matters, we don't want break it. 
It could also be `['darwin', '!darwin', 'darwin']`, so `uniq` may also break it.
for `man` field, I'm not familiar with `man` command, not sure we should do anything.
@keithamus thoughts?

fix: correct type of `man` `os` `cpu` field

---

index.js
test.js

Sort `eslintConfig` object, the ordering of key in my personal opinion, all keys can found [here](https://github.com/eslint/eslint/blob/acc0e47572a9390292b4e313b4a4bf360d236358/conf/config-schema.js).
But question is this too much for us?
If we start doing this kind of sorting, we may need sort other libs.
If not, we might want disable sorting for `eslintConfig`.

feat: sort `eslintConfig`

---

index.js

Rename this function, add `hasOwnProperty` check, so we won't add extra keys to the object

refactor: `sortProperty` -> `overProperty`

---

index.js
test.js

`overProperty` function is from #122
`pipe` function is from #121
please merge them first

refactor: use `pipe` and `overProperty`

---

index.js
test.js

feat: sort `prettier` field

---

package-lock.json
package.json

`validate-commit-msg` is deprecated. `commitlint` is recommanded by `validate-commit-msg` and `semantic-release`.

chore: replace `validate-commit-msg` with `commitlint`

---

index.js
test.js

the testes become hard to write, should we have a test lib that supports snap testing?

feat: sort `eslintConfig` deeper

---

index.js
tests/_helpers.js

```text
require('sort-package-json')({scripts: undefined})
Thrown:
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at sortScripts (<cwd>\node_modules\sort-package-json\index.js:117:24)
```

fix: missing type check on `sortScripts`

---

.github/workflows/ci.yml
cli.js
index.js
package-lock.json
package.json
tests/_helpers.js
tests/cli.js
tests/eslint.js
tests/fields.js
tests/main.js
tests/prettier.js
tests/white-space.js

This updates `prettier` to `2.0.4`. Note that the new version comes with several minor style updates as well, which requires code changes in the same commit (which is why #164 failed).
This also removes Node.js 8 from the GitHub Actions test matrix. @keithamus - If you require Node.js 8 compatibility, please close this PR (as well as #164). Node.js 8 is [no longer supported](https://nodejs.org/en/about/releases/), and Prettier 2 seems to be incompatible with it
Supersedes and closes #164

Update prettier to 2.0.4

---

package-lock.json
package.json

I couldn't figure out what Node versions you support or if you use semver, but this came up in a couple projects. Globby 11 drops node 8, and this project was not major version bumped.
https://github.com/keithamus/sort-package-json/pull/161/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R77
https://github.com/sindresorhus/globby/releases/tag/v11.0.0

fix: undo semver breaking globby update

---

index.d.ts

- add override for string version of function
- fix default export error in Typescript 3.9
With the changes, Typescirpt doesn't complain given this source:
```ts
import * as sortPackageJson from "sort-package-json";
import sortPackageJsonDefault from "sort-package-json";
import {
sortPackageJson as sortPackageJsonNamed,
ComparatorFunction,
Options,
SortPackageJsonFn
} from "sort-package-json";
const obj01: object = sortPackageJson({});
const obj02: object = sortPackageJson({}, {});
const obj03: object = sortPackageJson.default({});
const obj04: object = sortPackageJson.default({}, {});
const obj05: object = sortPackageJson.sortPackageJson({});
const obj06: object = sortPackageJson.sortPackageJson({}, {});
const obj07: object = sortPackageJsonDefault({});
const obj08: object = …
```

fix: typescript declarations

---

README.md

lint-staged no longer wants git-add add ran on it's behalf
https://github.com/okonet/lint-staged#v10
> From v10.0.0 onwards any new modifications to originally staged files will be automatically added to the commit. If your task previously contained a git add step, please remove this. The automatic behaviour ensures there are less race-conditions, since trying to run multiple git operations at the same time usually results in an error.

Update lint-staged instructions

---

README.md
defaultRules.md

Addresses https://github.com/keithamus/sort-package-json/issues/215

doc: add default rules

---

index.d.ts
index.js
package-lock.json
package.json
tests/options.js
tests/scripts.js
tests/types.ts
tsconfig.json
tslint.json

The fields option will override the values in the builtin fields array,
allowing users to signify that a given key should not be sorted, or sorted
in a particular way.

fix: stop sorting scripts

---

index.js
tests/scripts.js

This restores the default behaviour of sorting scripts alphabetically followed by pre & post _unless_ `npm-run-all` is a development dependency in the `package.json` being sorted.
Closes #220

feat: sort all scripts unless `npm-run-all` is a dependency

---

.github/workflows/pr.yml
.github/workflows/release.yml
.husky/commit-msg
.husky/pre-commit
README.md
cli.js
index.js
package-lock.json
package.json
tests/_helpers.js
tests/cli.js
tests/deps.js
tests/eslint.js
tests/fields.js
tests/main.js
tests/options.js
tests/prettier.js
tests/scripts.js
tests/white-space.js

Fixes #254
Fixes #247
Fixes #227
Closes #255
[BREAKING]: Require Node.js 12

refactor!: migrate to esm and update dependencies

---

.github/workflows/pr.yml
.github/workflows/release.yml
.husky/commit-msg
.husky/pre-commit
README.md
cli.js
index.js
package-lock.json
package.json
tests/_helpers.js
tests/cli.js
tests/deps.js
tests/eslint.js
tests/fields.js
tests/main.js
tests/options.js
tests/prettier.js
tests/scripts.js
tests/white-space.js

This reverts commit 3e4ff74ea4126a417c7e5aff6d6d9d8a4f7c8b8a.
#256 should have ben a breaking/major release.
CC/ @fisker @keithamus

Revert "refactor!: migrate to esm and update dependencies (#256)"

---

.github/workflows/pr.yml
.github/workflows/release.yml
.husky/commit-msg
.husky/pre-commit
README.md
cli.js
index.js
package-lock.json
package.json
tests/_helpers.js
tests/cli.js
tests/deps.js
tests/eslint.js
tests/fields.js
tests/main.js
tests/options.js
tests/prettier.js
tests/scripts.js
tests/white-space.js

Reverts keithamus/sort-package-json#259
Revert #256 back.
Please make sure we have a commit message footer this time https://github.com/keithamus/sort-package-json/pull/256#issuecomment-1087712876

refactor: migrate to esm and update dependencies

---

cli.js

added --version (-V) and --help (-h) options to the CLI for user interface.
```
Usage: sort-package-json [OPTION...] [FILE...]
Sort npm package.json files. Default: ./package.json
Strings passed as files are parsed as globs.
-c, --check                 check if FILES are sorted
-q, --quiet                  don't output success messages
-h, --help                   display this help and exit
-V, --version              display the version and exit
```
This help menu can be easily modified in cli.js. It includes the option from #281, but that could be easily removed if so desired.
```
sort-package-json 0.0.0-development
```
Or other such versions. The version is pulled from the project.json file in the cli script's directory.
This is found by reading process.env[1], using fs.realpathSync, to …

feat(cli): added --version and --help options

---

README.md

the header level was different than the rest

docs: adjust header for --stdin flag

---

index.d.ts

I get this error when I check my code that imports `sort-package-json`.
```
node_modules/sort-package-json/index.d.ts:49:1 - error TS1203: Export assignment cannot be used when
targeting ECMAScript modules. Consider using 'export default' or another module format instead.
49 export = sortPackageJsonExports
```
In this pull request, I've replaced the old syntax `export=` by `export default` and `export`. I've also removed `sortObjectBy` and `Field` that weren't being used.

fix: modernize type declarations

---

index.js
tests/scripts.js

Closes https://github.com/keithamus/sort-package-json/issues/308. Context: https://github.com/keithamus/sort-package-json/pull/232

feat: don’t sort scripts when `npm-run-all2` is installed

---

README.md

docs: added sortOrder descriptions to README.md

---

index.js
package-lock.json
package.json
tests/fields.js

https://github.com/keithamus/sort-package-json/pull/313 added the ability to deeply sort a `pnpm` object in `package.json`. This PR improves `pnpm` sorting in the following ways:
- groups similar fields together
- sorts `pnpm.overrides` entries with the same package name using semver rather than alphabetically
**Example:**
Before this change:
```
"pnpm": {
"overrides": {
"@react-stately/selection@~3.10.3": "3.10.3",
"@react-stately/selection@~3.7.0": "3.7.0"
}
}
```
After this change:
```
"pnpm": {
"overrides": {
"@react-stately/selection@~3.7.0": "3.7.0",
"@react-stately/selection@~3.10.3": "3.10.3"
}
}
```

feat: improve pnpm sorting

---

index.js
tests/scripts.js

feat: sort pre/post scripts with colon together

---

index.js
tests/scripts.js

Add support for npm-run-all2 to prevent script sorting when sequential wildcard execution is needed.
Closes #359

fix: prevent sorting when npm-run-all2 is used

---

package-lock.json
package.json

This PR removes `ncp` that seems to be unused:
- it was added in #316
- became unused in #346
The `build` script is changing between these two PRs. Looks like that was the only usage of `ncp`. Unless I missed something.

chore: remove `ncp`
